[package]
name = "rust-core"
version = "0.1.0"
edition = "2024"

[dependencies]
lopdf = "0.36.0"
napi = { version = "3.1.3", features = ["napi6"] }
napi-derive = "3.1.1"


[lib]
crate-type = ["cdylib"]