// Auto-generated by NAPI-RS
import { createRequire } from "module";
const require = createRequire(import.meta.url);

const {
  getPageCount,
  signPdf,
  signPdfLegacy,
  signPdfWithVisibleText,
  signPdfWithOptions,
  getPdfInfoBeforeSigning,
  generateSigningKeyPair,
  getKeyInfoFromJson,
  signPdfWithKey,
  verifyPdfSignature,
  getPdfChecksum,
} = require("./index.node");

export {
  getPageCount,
  signPdf,
  signPdfLegacy,
  signPdfWithVisibleText,
  signPdfWithOptions,
  getPdfInfoBeforeSigning,
  generateSigningKeyPair,
  getKeyInfoFromJson,
  signPdfWithKey,
  verifyPdfSignature,
  getPdfChecksum,
};
