/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getPageCount(filePath: string): number

export declare function getPdfInfoBeforeSigning(filePath: string): number

export declare function signPdf(filePath: string, signatureText: string): void
