// Auto-generated by NAPI-RS
import { createRequire } from "module";
const require = createRequire(import.meta.url);

const {
  getPageCount,
  signPdf,
  getPdfInfoBeforeSigning,
} = require("./index.node");

export { getPageCount, signPdf, getPdfInfoBeforeSigning };
