name: SoloPDF CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-core:
    runs-on: ubuntu-latest
    name: Build and Test Rust Core

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust-core/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust-core/Cargo.lock') }}

      - name: Validate Rust code
        working-directory: rust-core
        run: |
          cargo fmt --check
          cargo clippy --all-targets --all-features -- -D warnings
          cargo test --verbose

      - name: Build NAPI module
        working-directory: rust-core
        run: |
          npm install
          npx napi build --release

      - name: Generate test PDFs
        working-directory: rust-core
        run: |
          mkdir -p ../executed/generated-pdfs
          cargo run --bin generate_test_pdfs -- ../executed/generated-pdfs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-core-build
          path: |
            rust-core/index.node
            rust-core/index.js
            rust-core/index.d.ts

  node-wrapper:
    runs-on: ubuntu-latest
    name: Build and Test Node Wrapper
    needs: rust-core

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.13.1"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "node-wrapper/pnpm-lock.yaml"

      - name: Download Rust artifacts
        uses: actions/download-artifact@v4
        with:
          name: rust-core-build
          path: rust-core/

      - name: Setup and test
        run: |
          node scripts/setup-execution-env.mjs
          cd node-wrapper
          pnpm install --frozen-lockfile
          pnpm lint
          pnpm test
          pnpm build

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          directory: node-wrapper/coverage
          flags: node-tests
