name: SoloPDF CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  rust-core:
    runs-on: ubuntu-latest
    name: Build and Test Rust Core

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Setup Node.js (for NAPI)
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust-core/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust-core/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Check Rust code
        working-directory: rust-core
        run: cargo check

      - name: Test Rust core
        working-directory: rust-core
        run: cargo test

      - name: Build NAPI addon
        working-directory: rust-core
        run: cargo build --release

      - name: Upload Rust build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-core-build
          path: |
            rust-core/target/release/librust_core.so
            rust-core/target/release/rust_core.node
            rust-core/index.node
          if-no-files-found: ignore

  node-wrapper:
    runs-on: ubuntu-latest
    name: Build and Test Node Wrapper
    needs: rust-core

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.13.1"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "node-wrapper/pnpm-lock.yaml"

      - name: Install Node.js dependencies
        working-directory: node-wrapper
        run: pnpm install --frozen-lockfile

      - name: Run linter
        working-directory: node-wrapper
        run: pnpm lint

      - name: Run tests
        working-directory: node-wrapper
        run: pnpm test

      - name: Build TypeScript
        working-directory: node-wrapper
        run: pnpm build

      - name: Upload Node.js build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-wrapper-build
          path: node-wrapper/dist/

  integration-test:
    runs-on: ubuntu-latest
    name: Integration Test
    needs: [rust-core, node-wrapper]
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Download Rust artifacts
        uses: actions/download-artifact@v4
        with:
          name: rust-core-build
          path: rust-core/

      - name: Download Node.js artifacts
        uses: actions/download-artifact@v4
        with:
          name: node-wrapper-build
          path: node-wrapper/dist/

      - name: Verify artifacts exist
        run: |
          echo "Checking Rust artifacts:"
          find rust-core/ -name "*.node" -o -name "*.so" || echo "No Rust artifacts found"
          echo "Checking Node.js artifacts:"
          find node-wrapper/dist/ -type f || echo "No Node.js artifacts found"
