name: SoloPDF CI

# Note: macOS support temporarily disabled due to NAPI linking issues
# Working platforms: Windows x64, Linux x64

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-binaries:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: win32-x64-msvc
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: linux-x64-gnu
          # TODO: macOS support - NAPI linking issues need to be resolved
          # - target: x86_64-apple-darwin
          #   os: macos-13
          #   name: darwin-x64
          # - target: aarch64-apple-darwin
          #   os: macos-14
          #   name: darwin-arm64

    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          target: ${{ matrix.target }}

      - name: Verify Rust setup
        run: |
          echo "=== Rust Setup Verification ==="
          rustc --version
          cargo --version
          rustup show
          echo "Installed targets:"
          rustup target list --installed
          echo "Default host: $(rustc -vV | grep host | cut -d' ' -f2)"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Use Node.js 20 for better NAPI compatibility
          node-version: "20.x"

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust-core/target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('rust-core/Cargo.lock') }}

      - name: Validate Rust code (Linux only)
        if: matrix.os == 'ubuntu-latest'
        working-directory: rust-core
        run: |
          cargo fmt --check
          cargo clippy --all-targets --all-features -- -D warnings
          cargo test --verbose

      - name: Build NAPI module
        working-directory: rust-core
        shell: bash
        run: |
          # Install dependencies first
          npm install

          # Build for the target
          echo "Building for target: ${{ matrix.target }}"
          echo "Runner OS: ${{ matrix.os }}"
          echo "Runner architecture: $(uname -m)"
          echo "Node architecture: $(node -p 'process.arch')"

          # Build with explicit target for Windows and Linux
          npx napi build --release --platform --target ${{ matrix.target }}

      - name: Verify build output
        working-directory: rust-core
        shell: bash
        run: |
          echo "Checking build artifacts..."
          ls -la *.node *.js *.d.ts 2>/dev/null || echo "No build artifacts found"

      - name: Generate test PDFs (Linux only)
        if: matrix.os == 'ubuntu-latest'
        working-directory: rust-core
        shell: bash
        run: |
          mkdir -p ../executed/generated-pdfs
          cargo run --bin generate_test_pdfs -- ../executed/generated-pdfs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.name }}
          path: |
            rust-core/*.node
            rust-core/index.js
            rust-core/index.d.ts

  node-wrapper:
    runs-on: ubuntu-latest
    name: Build and Test Node Wrapper
    needs: build-binaries

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.13.1"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "node-wrapper/pnpm-lock.yaml"

      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: binary-linux-x64-gnu
          path: rust-core/

      - name: Setup and test
        run: |
          node scripts/setup-execution-env.mjs
          cd node-wrapper
          pnpm install --no-frozen-lockfile
          pnpm lint
          pnpm test
          pnpm build

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          directory: node-wrapper/coverage
          flags: node-tests
